IMAGE_NAME = "ubuntu/bionic64"
N = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    
    
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "10.0.0.20"
        master.vm.hostname = "k8s-master"
        # master.vm.provision "shell", inline = "echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCs57cxhCud+1W48+M5IFB88lJCGJ8QHnR7C/U+rRlI7TxfKo9YNRaFaMBTBvLbWgsXW3xXhPs9xhY3y+vWljooXrSM6ls0sDCd6Oi8XeTGDl2tUW9/BHQYCQas1x08x9eDVqppJu0Nsw6qJ7P16KQEUqJhMW0wLABFbUm4vkY92/oMOGL24O336z1aJHZFC9V2buzRqy9Pr2FJ7bo7R/04L/6vh+7Xkm2SbvA2Bwmp119IVA8iFuFhZc6aPs3UDtNsvDVYTZunrjxMRQI9GelAdS7gMbmGBa1Ar5i+zl5v98mFdrEWwGH8UKSOCf8f+SNEFnA0HtAArl/u+0/YCsPzN9Zcj/8Oh3oJJxtjImMohYCPPN9PGPrQwzArMbjZowkLPsKIQq9YgxoM8ar1fqo8pg5rcxuLmRN3YEvn2KKQEADWBTz+egHtzMp1GlBJr46lRMy7xZF+hn2UY+uLA1OwxYOu/QcYrxMb4YXG/V85ybSmheJbAFEMZVowggIwGWs= marcos@marcos-laptop' >> /home/vagrant/.ssh/authorized_keys"
        master.vm.provision "shell", path: "k8s_config/scripts/copy_key.sh"
        master.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--memory", "2048"]
            v.customize ["modifyvm", :id, "--cpus", "2"]
        end
    end
    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "10.0.0.#{i + 20}"
            node.vm.hostname = "node-#{i}"
            # node.vm.provision "shell", inline: "echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCs57cxhCud+1W48+M5IFB88lJCGJ8QHnR7C/U+rRlI7TxfKo9YNRaFaMBTBvLbWgsXW3xXhPs9xhY3y+vWljooXrSM6ls0sDCd6Oi8XeTGDl2tUW9/BHQYCQas1x08x9eDVqppJu0Nsw6qJ7P16KQEUqJhMW0wLABFbUm4vkY92/oMOGL24O336z1aJHZFC9V2buzRqy9Pr2FJ7bo7R/04L/6vh+7Xkm2SbvA2Bwmp119IVA8iFuFhZc6aPs3UDtNsvDVYTZunrjxMRQI9GelAdS7gMbmGBa1Ar5i+zl5v98mFdrEWwGH8UKSOCf8f+SNEFnA0HtAArl/u+0/YCsPzN9Zcj/8Oh3oJJxtjImMohYCPPN9PGPrQwzArMbjZowkLPsKIQq9YgxoM8ar1fqo8pg5rcxuLmRN3YEvn2KKQEADWBTz+egHtzMp1GlBJr46lRMy7xZF+hn2UY+uLA1OwxYOu/QcYrxMb4YXG/V85ybSmheJbAFEMZVowggIwGWs= marcos@marcos-laptop' >> /home/vagrant/.ssh/authorized_keys"
            node.vm.provision "shell", path: "k8s_config/scripts/copy_key.sh"
            node.vm.provider "virtualbox" do |v|
                v.customize ["modifyvm", :id, "--memory", "3072"]
                v.customize ["modifyvm", :id, "--cpus", "2"]
            end
        end
    end
end


Vagrant.configure("2") do |conf|
    conf.ssh.insert_key = false

    # conf.vm.provider "virtualbox" do |c|
    #     c.memory = 1024
    #     c.cpus = 1
    # end
      
    conf.vm.define "controller" do |controller|
        controller.vm.box = IMAGE_NAME
        controller.vm.network "private_network", ip: "10.0.0.10"
        controller.vm.hostname = "controller"
        controller.vm.provision "shell", path: "k8s_config/scripts/install_ansible.sh"

        controller.vm.provision "file", source: "k8s_config", destination: "/home/vagrant/k8s_config"

        # controller.vm.provision "file", source: "k8s_config/hosts", destination: "~/"
        controller.vm.provision "file", source: "keys/key", destination: "~/.ssh/"
        
        controller.vm.provision "shell", inline: "ansible-playbook -i /home/vagrant/k8s_config/hosts /home/vagrant/k8s_config/main_config.yml -u vagrant"
        controller.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--memory", "1024"]
            v.customize ["modifyvm", :id, "--cpus", "1"]
        end
        
    end
end