---
- hosts: all
  become: true
  tasks:
    # - name: Wait for kubernetes to start
    #   wait_for:
    #     port: 6443
    #     delay: 120

    - name: copy config files to target
      copy:
        src: k8s-app-deploy
        dest: /home/vagrant/
        mode: 0644

    # - name: Change permissions for bash script
    #   file:
    #     path: /home/vagrant/k8s-app-deploy/deploy-script.sh
    #     mode: 0655

    - name: Run script to deploy everything
      shell: bash /home/vagrant/k8s-app-deploy/deploy-script.sh "{{ node_ip }}" "{{ node_port }}"

    #--kubeconfig=/home/dialog/.kube/config
