---
- hosts: all
  become: no
  tasks:
    - name: create local dns file
      lineinfile:
        path: ./hosts
        line: "{{ node_ip }} {{ name }}"
        create: yes
      delegate_to: 127.0.0.1

- hosts: all
  vars:
    contents: "{{ lookup('file', './hosts') }}"
  tasks:
    - debug: msg="the value of hosts is {{ contents }}"
