---
- hosts: all
  become: yes
  roles:
    - common

- hosts: k8s-master
  become: yes
  roles:
    - master

- hosts: node-1
  become: yes
  roles:
    - node

- hosts: k8s-master
  become: yes
  roles:
    - deploy_app
