{
 "title": "Consumer - Input",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consumer partitions - topic input",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic=\"input\"}"
    }
   ]
  },
  {
   "title": "Consumer partitions - topic input",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic=\"input\"}"
    }
   ]
  },
  {
   "title": "Consumer Offset - topic input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset{consumergroup=\"my-group\",partition=\"0\",topic=\"input\"}"
    }
   ]
  },
  {
   "title": "Consumer lag - topic input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{consumergroup=\"my-group\",partition=\"0\",topic=\"input\"}"
    }
   ]
  },
  {
   "title": "Consumer partitions - topic input",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic=\"output\"}"
    }
   ]
  }
 ]
}